"""rename location fields

Revision ID: 3154dee84a85
Revises: 009
Create Date: 2026-09-20 14:29:45.484683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3154dee84a85'
down_revision: Union[str, Sequence[str], None] = '009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Safely drop custom_test if it exists
    dep_cols = [c['name'] for c in inspector.get_columns('deployments')]
    if 'custom_test' in dep_cols:
        op.drop_column('deployments', 'custom_test')

    loc_cols = [c['name'] for c in inspector.get_columns('locations')]
    if 'district' not in loc_cols:
        op.add_column('locations', sa.Column('district', sa.String(), nullable=True))
    if 'state' not in loc_cols:
        op.add_column('locations', sa.Column('state', sa.String(), nullable=True))
    if 'country' in loc_cols:
        op.drop_column('locations', 'country')
    if 'datacenter_tier' in loc_cols:
        op.drop_column('locations', 'datacenter_tier')
    if 'city' in loc_cols:
        op.drop_column('locations', 'city')



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('datacenter_tier', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_locations_company_id', 'locations', ['company_id'], unique=False)
    op.drop_column('locations', 'state')
    op.drop_column('locations', 'district')
    op.add_column('deployments', sa.Column('custom_test', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_deployment_phase_remarks_phase'), table_name='deployment_phase_remarks')
    op.drop_index(op.f('ix_deployment_phase_remarks_deployment_id'), table_name='deployment_phase_remarks')
    op.create_index('idx_deployment_phase_remarks_phase', 'deployment_phase_remarks', ['phase'], unique=False)
    op.create_index('idx_deployment_phase_remarks_deployment_id', 'deployment_phase_remarks', ['deployment_id'], unique=False)
    op.drop_index(op.f('ix_credential_versions_deployment_id'), table_name='credential_versions')
    op.drop_index(op.f('ix_credential_versions_credential_id'), table_name='credential_versions')
    op.create_index('idx_credential_versions_deployment_id', 'credential_versions', ['deployment_id'], unique=False)
    op.create_index('idx_credential_versions_credential_id', 'credential_versions', ['credential_id'], unique=False)
    op.create_index('ix_company_contacts_company_id', 'company_contacts', ['company_id'], unique=False)
    # ### end Alembic commands ###
